### ISSUE TITLE
psych engine crashes when trying to enter anything that contains WeekData

### ISSUE THREAD

**Issue by Frakist** [jigsaw-4277821/FNF-Porting-Stuff-Psych-Engine#2]
im trying to port my mod to mobile, and it wont work. i dont need mods enabled because 1. its tedious for the fanbase to download it and 2. everything in my mod is hardcoded (so i dont need mod support). when disabling mods on desktop everything seems fine until i try it on my phone, and even the SUtil crash check doesnt say anything

**Comment by Randomxdp** [comment]
> im trying to port my mod to mobile, and it wont work. i dont need mods enabled because 1. its tedious for the fanbase to download it and 2. everything in my mod is hardcoded (so i dont need mod support). when disabling mods on desktop everything seems fine until i try it on my phone, and even the SUtil crash check doesnt say anything

hi i can help you with this

**Comment by Frakist** [comment]
> > im trying to port my mod to mobile, and it wont work. i dont need mods enabled because 1. its tedious for the fanbase to download it and 2. everything in my mod is hardcoded (so i dont need mod support). when disabling mods on desktop everything seems fine until i try it on my phone, and even the SUtil crash check doesnt say anything
> 
> hi i can help you with this

do you know a fix to this?

**Comment by Randomxdp** [comment]
O

**Comment by Randomxdp** [comment]
> > > im trying to port my mod to mobile, and it wont work. i dont need mods enabled because 1. its tedious for the fanbase to download it and 2. everything in my mod is hardcoded (so i dont need mod support). when disabling mods on desktop everything seems fine until i try it on my phone, and even the SUtil crash check doesnt say anything
> > 
> > 
> > hi i can help you with this
> 
> do you know a fix to this?

Sorry i forgor abt you ☹️
